name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: find and build mod
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" -print -quit)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "КРИТИЧЕСКАЯ ОШИБКА: Файл gradlew вообще не найден!"
            exit 1
          fi
          MOD_DIR=$(dirname "$GRADLEW_PATH")
          cd "$MOD_DIR"
          chmod +x ./gradlew
          ./gradlew build --no-daemon
          
          echo "=== СПИСОК ВСЕХ СОЗДАННЫХ JAR ФАЙЛОВ ==="
          find . -name "*.jar"
          echo "========================================"

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: "**/build/libs/*.jar"

